export enum OrderStatus {
	ORCADA = 'ORÇADA',
	APROVADA = 'APROVADA',
	ABERTA = 'ABERTA',
	REJEITADA = 'REJEITADA',
	REDIRECIONADA = 'REDIRECIONADA',
	PAGA = 'PAGA',
	FINALIZADA = 'FINALIZADA',
	ARRUMADA = 'ARRUMADA',
}
