CREATE TABLE users (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20)  NOT NULL CHECK (role IN ('CLIENTE','FUNCIONARIO'))
);

ALTER TABLE users ADD CONSTRAINT uk_users_email UNIQUE (email);