CREATE TABLE IF NOT EXISTS category (
  id BIGSERIAL PRIMARY KEY,
  nome VARCHAR(80) NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NULL,
  CONSTRAINT uk_category_nome UNIQUE (nome)
);