CREATE TABLE IF NOT EXISTS historico_alteracao (
  id BIGSERIAL PRIMARY KEY,
  solicitacao_id BIGINT NOT NULL REFERENCES solicitacao(id) ON DELETE CASCADE,
  estado_anterior VARCHAR(30) NULL CHECK (estado_anterior IN ('ABERTA','ORCADA','REJEITADA','APROVADA','REDIRECIONADA','ARRUMADA','PAGA','FINALIZADA')),
  estado_novo VARCHAR(30) NOT NULL CHECK (estado_novo IN ('ABERTA','ORCADA','REJEITADA','APROVADA','REDIRECIONADA','ARRUMADA','PAGA','FINALIZADA')),
  data_hora TIMESTAMP NOT NULL DEFAULT NOW(),
  autor_id BIGINT REFERENCES users(id) ON DELETE RESTRICT,
  destino_id BIGINT NULL REFERENCES users(id) ON DELETE RESTRICT
  );