CREATE TABLE historico_alteracao (
  id BIGSERIAL PRIMARY KEY,
  order_id BIGINT NOT NULL,
  autor_id BIGINT NOT NULL,
  estado_anterior VARCHAR(30) NOT NULL CHECK (estado_anterior IN ('ABERTA','ORCADA','APROVADA','REJEITADA','REDIRECIONADA','PAGA','FINALIZADA','ARRUMADA')),
  estado_novo VARCHAR(30) NOT NULL CHECK (estado_novo IN ('ABERTA','ORCADA','APROVADA','REJEITADA','REDIRECIONADA','PAGA','FINALIZADA','ARRUMADA')),
  data_hora TIMESTAMP  NOT NULL,
  CONSTRAINT fk_hist_order FOREIGN KEY (order_id) REFERENCES orders(id),
  CONSTRAINT fk_hist_autor FOREIGN KEY (autor_id) REFERENCES users(id)
);